version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: rag-chat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rag_chat
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  rag-chat-service:
    build: .
    container_name: rag-chat-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npx tsx src/app.ts
    restart: unless-stopped

volumes:
  pgdata:
